# Automatically build the project and run any configured tests for every push
# and submitted pull request.
name: build
on:
  pull_request:
  push:
    branches:
      - '*'
    tags:
      - 'v*' # Si attiva quando fai push di un tag che inizia con "v" (es. v1.0.0)

# Permessi necessari al bot di GitHub per creare la release
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build

      - name: capture build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: build/libs/

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v3
        with:
          files: build/libs/*.jar

      - name: Publish to Modrinth
        if: startsWith(github.ref, 'refs/tags/')
        uses: Kira-NT/mc-publish@v3
        with:
          modrinth-id: 'PsNb5dTq'
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          # Specifica il jar da caricare (attenzione a non includere i -dev.jar o -sources.jar se non li vuoi su Modrinth)
          files: build/libs/!(*-dev|-sources).jar
          name: ${{ github.ref_name }}-26.2 - MC-Networking
          version: ${{ github.ref_name }}-26.2
          version-type: release
          changelog-file: CHANGELOG.md
          loaders: fabric
          game-versions: 26.2
          dependencies: |
            fabric-api@required