# Automatically build the project and run any configured tests for every push
# and submitted pull request.
name: build
on:
  pull_request:
  push:
    branches:
      - '*'
    tags:
      - 'v*' # Si attiva quando fai push di un tag che inizia con "v" (es. v1.0.0)

# Permessi necessari al bot di GitHub per creare la release
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Leggi versioni da gradle.properties
        id: props
        run: |
          # Estrae il valore dopo l'uguale rimuovendo eventuali spazi
          MOD_VER=$(grep '^mod_version' gradle.properties | cut -d'=' -f2 | tr -d '[:space:]')
          MC_VER=$(grep '^minecraft_version' gradle.properties | cut -d'=' -f2 | tr -d '[:space:]')
          
          echo "mod_version=\(MOD_VER" >> "\)GITHUB_OUTPUT"
          echo "minecraft_version=\(MC_VER" >> "\)GITHUB_OUTPUT"

      - name: Aggiorna versione nel CHANGELOG.md
        run: |
          FULL_VER="v\({{ steps.props.outputs.mod_version }}-\){{ steps.props.outputs.minecraft_version }}"
          sed -i "s/{{VERSION}}/$FULL_VER/g" CHANGELOG.md

      - name: build
        run: ./gradlew build

      - name: clean unwanted jars
        run: rm -f build/libs/*-sources.jar build/libs/*-dev.jar

      - name: capture build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: build/libs/

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v3
        with:
          files: build/libs/*.jar

      - name: Publish to Modrinth
        if: startsWith(github.ref, 'refs/tags/')
        uses: Kira-NT/mc-publish@v3
        with:
          modrinth-id: 'PsNb5dTq'
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: build/libs/*.jar
          name: ${{ github.ref_name }} - MC-Networking
          version: ${{ github.ref_name }}
          version-type: release
          changelog-file: CHANGELOG.md
          loaders: fabric
          game-versions: ${{ steps.props.outputs.minecraft_version }}
          dependencies: |
            fabric-api@required